---
name: test

on:
  push:
    branches:
      - "*"

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2

      - name: Test init command
        run: ./bin/stack init

      - name: Test up command
        run: ./bin/stack up -d

      - name: Test list command
        run: ./bin/stack list

      - name: Test compose command
        run: ./bin/stack compose --version

      - name: Test proxied command
        run: ./bin/stack php --version

      - name: Test down command
        run: ./bin/stack down --volumes
