---
version: "3"

services:
  runtime:
    image: ${STACK_RUNTIME_IMAGE:?}:${STACK_RUNTIME_TAG}
    restart: always
    ports:
      - "${STACK_HTTP_PORT:?}:80"
      - "${STACK_HTTPS_PORT:?}:443"
    volumes:
      - "${STACK_DATA_DIR:?}:${STACK_CONTAINER_DATA_DIR:?}"
      - "${STACK_DATA_DIR:?}/runtime.yml:/opt/runtime/config/custom.yml:ro"
      - "${STACK_WORKDIR:?}/runtime.yml:/opt/runtime/config/runtime.yml:ro"

volumes:
  sip:
    driver: local
