---
services:
  influxdb:
    image: "${STACK_INFLUXDB_IMAGE:?}:${STACK_INFLUXDB_TAG:?}"
    restart: always
    environment:
      DOCKER_INFLUXDB_INIT_MODE: "setup"
      DOCKER_INFLUXDB_INIT_ORG: ${STACK_INFLUXDB_ORG:?}
      DOCKER_INFLUXDB_INIT_BUCKET: ${STACK_INFLUXDB_BUCKET:?}
      DOCKER_INFLUXDB_INIT_USERNAME: ${STACK_INFLUXDB_USERNAME:?}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${STACK_INFLUXDB_PASSWORD:?}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${STACK_INFLUXDB_ADMIN_TOKEN:?}
    ports:
      - ${STACK_INFLUXDB_PORT:?}:8086
    volumes:
      - "influxdb:/var/lib/influxdb2"
      - "${STACK_DATA_DIR:?}:${STACK_CONTAINER_DATA_DIR:?}"
    healthcheck:
      test: ["CMD", "curl", "-sI", "http://127.0.0.1:8086/ping"]
      interval: 5s
      timeout: 5s
      retries: 6

volumes:
  influxdb:
    driver: local
