---
services:
  node-red:
    image: nodered/node-red:${STACK_NODERED_VERSION:-1.3.6}
    restart: always
    volumes:
      - "node-red:/data"
      - "${STACK_DATA_DIR:?}:${STACK_CONTAINER_DATA_DIR:?}"

volumes:
  node-red:
    driver: local
