---
services:
  node-red:
    image: ${STACK_NODERED_IMAGE:?}:${STACK_NODERED_TAG:?}
    restart: always
    volumes:
      - "node-red:/data"
      - "${STACK_DATA_DIR:?}:${STACK_CONTAINER_DATA_DIR:?}"

volumes:
  node-red:
    driver: local
