---
services:
  phpmyadmin:
    image: "${STACK_PHPMYADMIN_IMAGE:?}:${STACK_PHPMYADMIN_TAG:?}"
    restart: always
    environment:
      DATABASE_HOST: mysql
      PHP_UPLOAD_MAX_FILESIZE: 2G
      PHPMYADMIN_ABSOLUTE_URI: "/svc/phpmyadmin/"
